<a href="https://colab.research.google.com/github/Venkatesh-80/Machine-Learning-Foundation/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Group by in pandas**

In [1]:
import numpy as np
import pandas as pd

In [16]:
data={
    "Name": ["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer"],
    "Age": [22,23,None,22,25,24,26],
    "Marks": [85,None,88,90,56,72,None],
    "Subject": ["Math","Science","Math","Science","Math","Science","Science"]
}
df=pd.DataFrame(data)
print(df)

       Name   Age  Marks  Subject
0      Aman  22.0   85.0     Math
1    Saurav  23.0    NaN  Science
2     Karan   NaN   88.0     Math
3   Shubham  22.0   90.0  Science
4  Abhishek  25.0   56.0     Math
5      None  24.0   72.0  Science
6    Sameer  26.0    NaN  Science

In [17]:
df.groupby("Subject")["Marks"].mean()   #By default the operation ignores NAN VAlues

Subject
Math       76.333333
Science    81.000000
Name: Marks, dtype: float64

In [12]:
df.groupby("Subject")["Marks"].median()

Subject
Math       85.0
Science    81.0
Name: Marks, dtype: float64

In [13]:
df.groupby("Subject")["Marks"].sum()

Subject
Math       229.0
Science    162.0
Name: Marks, dtype: float64

In [15]:
df.groupby("Subject")["Name"].count()

Subject
Math       3
Science    3
Name: Name, dtype: int64

In [20]:
 #Multiple Aggregation
df.groupby("Subject")["Marks"].agg(["mean","median","sum"])

              mean  median    sum
Subject
Math     76.333333    85.0  229.0
Science  81.000000    81.0  162.0

In [23]:
df.groupby("Subject")["Marks"].agg(["min","max","count"])

          min   max  count
Subject
Math     56.0  88.0      3
Science  72.0  90.0      2

In [24]:
#Group Multiple Columns
df.groupby(["Subject","Name"])["Marks"].mean()

Subject  Name
Math     Abhishek    56.0
         Aman        85.0
         Karan       88.0
Science  Sameer       NaN
         Saurav       NaN
         Shubham     90.0
Name: Marks, dtype: float64

In [40]:
data={
    "Name": ["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer",None,"Venkatesh","Hari"],
    "Department": ["IT","CSE","Sales","HR",None,"CSE","Sales","HR","IT","CSE"],
    "Role": ["Manager","Developer","Analyst",None,"Data Scientist","Manager","Senior Manager","Manager",None,None],
    "Experience":[10,20,30,40,25,23,8,2,4,5],
    "Salary":[100000,23333,89999,99898,808097,90877,170000,20000,90000,100000],
    "Score": [10,20,30,40,50,60,70,80,90,99]
}
df=pd.DataFrame(data)
print(df)

        Name Department            Role  Experience  Salary  Score
0       Aman         IT         Manager          10  100000     10
1     Saurav        CSE       Developer          20   23333     20
2      Karan      Sales         Analyst          30   89999     30
3    Shubham         HR            None          40   99898     40
4   Abhishek       None  Data Scientist          25  808097     50
5       None        CSE         Manager          23   90877     60
6     Sameer      Sales  Senior Manager           8  170000     70
7       None         HR         Manager           2   20000     80
8  Venkatesh         IT            None           4   90000     90
9       Hari        CSE            None           5  100000     99

In [28]:
df.groupby("Department")["Salary"].mean()

Department
CSE       71403.333333
HR        59949.000000
IT       332699.000000
Sales    129999.500000
Name: Salary, dtype: float64

In [29]:
df.groupby("Role")["Score"].mean()

Role
Analyst           30.0
Data Scientist    50.0
Developer         50.0
Manager           35.0
Senior Manager    70.0
Name: Score, dtype: float64

In [32]:
df.groupby("Department")["Score"].count()

Department
CSE      3
HR       2
IT       2
Sales    2
Name: Score, dtype: int64

In [33]:
df.groupby("Department")["Name"].count()

Department
CSE      2
HR       1
IT       2
Sales    2
Name: Name, dtype: int64

In [34]:
df.groupby("Department").size()

Department
CSE      3
HR       2
IT       2
Sales    2
dtype: int64

In [36]:
df.groupby("Department")["Salary"].agg(["mean","max","min","count"]) #Finding agg functions for salary based on Department

                     mean     max    min  count
Department
CSE          71403.333333  100000  23333      3
HR           59949.000000   99898  20000      2
IT           95000.000000  100000  90000      2
Sales       129999.500000  170000  89999      2

In [37]:
df.groupby("Role")["Score"].agg(["mean","max","min","count"]) #Finding agg functions for score based on Role

                mean  max  min  count
Role
Analyst         30.0   30   30      1
Data Scientist  50.0   50   50      1
Developer       50.0   80   20      2
Manager         35.0   60   10      2
Senior Manager  70.0   70   70      1

In [41]:
df.groupby(["Department","Role"])["Salary"].mean()

Department  Role
CSE         Developer          23333.0
            Manager            90877.0
HR          Manager            20000.0
IT          Manager           100000.0
Sales       Analyst            89999.0
            Senior Manager    170000.0
Name: Salary, dtype: float64

In [42]:
df.groupby(["Department","Experience"])["Score"].mean()

Department  Experience
CSE         5             99.0
            20            20.0
            23            60.0
HR          2             80.0
            40            40.0
IT          4             90.0
            10            10.0
Sales       8             70.0
            30            30.0
Name: Score, dtype: float64