<a href="https://colab.research.google.com/github/Venkatesh-80/Machine-Learning-Foundation/blob/main/PandasExcersice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [8]:
data = {
    "name": ["Aman","Saurav","karan","shubham","abhishek",None,"Sammer"],
    "age": [22,23,None,22,25,24,26],
    "marks":[85,None,88,90,56,72,None],
    "subject":["math","physics","math","chemistry","math","physics","chemistry"]

}
df = pd.DataFrame(data)
print(df)

       name   age  marks    subject
0      Aman  22.0   85.0       math
1    Saurav  23.0    NaN    physics
2     karan   NaN   88.0       math
3   shubham  22.0   90.0  chemistry
4  abhishek  25.0   56.0       math
5      None  24.0   72.0    physics
6    Sammer  26.0    NaN  chemistry

In [9]:
print(df.describe())

             age      marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

In [10]:
print(df.dtypes)

name        object
age        float64
marks      float64
subject     object
dtype: object

In [11]:
print(df.shape)

(7, 4)

In [12]:
print(df["marks"]>80)

0     True
1    False
2     True
3     True
4    False
5    False
6    False
Name: marks, dtype: bool

In [13]:
df[(df["age"]>=22) & (df["marks"]>80) ]

      name   age  marks    subject
0     Aman  22.0   85.0       math
3  shubham  22.0   90.0  chemistry

In [14]:
df["subject"].value_counts()

subject
math         3
physics      2
chemistry    2
Name: count, dtype: int64

In [15]:
df.sort_values("marks",ascending=False)

       name   age  marks    subject
3   shubham  22.0   90.0  chemistry
2     karan   NaN   88.0       math
0      Aman  22.0   85.0       math
5      None  24.0   72.0    physics
4  abhishek  25.0   56.0       math
1    Saurav  23.0    NaN    physics
6    Sammer  26.0    NaN  chemistry

In [16]:
top = df["marks"].nlargest(2)
print(top)

3    90.0
2    88.0
Name: marks, dtype: float64

In [17]:
lowest_mark = df['marks'].min()
lowest_marks_students = df[df['marks'] == lowest_mark]
print(lowest_marks_students)

       name   age  marks subject
4  abhishek  25.0   56.0    math

In [18]:
print('Missing values before handling:')
print(df.isnull().sum())

Missing values before handling:
name       1
age        1
marks      2
subject    0
dtype: int64

In [19]:
cleaned_df = df.dropna()
print('DataFrame after removing rows with any missing values:')
print(cleaned_df)
print('\nMissing values in cleaned_df:')
print(cleaned_df.isnull().sum())

DataFrame after removing rows with any missing values:
       name   age  marks    subject
0      Aman  22.0   85.0       math
3   shubham  22.0   90.0  chemistry
4  abhishek  25.0   56.0       math

Missing values in cleaned_df:
name       0
age        0
marks      0
subject    0
dtype: int64

In [20]:
missing_marks_rows = df[df['marks'].isnull()]
print('Rows with missing marks:')
print(missing_marks_rows)

Rows with missing marks:
     name   age  marks    subject
1  Saurav  23.0    NaN    physics
6  Sammer  26.0    NaN  chemistry

In [21]:
print('Shape of original DataFrame (df):', df.shape)
print('Shape of cleaned DataFrame (cleaned_df):', cleaned_df.shape)

Shape of original DataFrame (df): (7, 4)
Shape of cleaned DataFrame (cleaned_df): (3, 4)

In [22]:
df.describe()

             age      marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000